#####################################################################
# The code was modified by the one composed
#	by Xihao Li, Zilin Li.
# https://github.com/xihaoli/STAARpipeline-Tutorial
#
# Gene-centric analysis for noncoding rare variants of protein-coding 
# genes using STAARpipeline
#####################################################################
rm(list=ls())

##### Parse parameters #####
args = commandArgs(trailingOnly=TRUE)
if (length(args)!=4) {
        cat("\n")
        cat("Usage: Rscript --vanilla STAARpipeline_Gene_Centric_Noncoding.r <Annotation_Rdata_DIR> <GENESIS_null_model> <arrayID> <Out_Prefix>\n")
        cat("\tInput:\n")
        cat("\t\t<Annotation_Rdata_DIR>: The folder contains agds_dir.Rdata, Annotation_name_catalog.Rdata, and jobs_num.Rdata generated by Association_Analysis_PreStep.r.\n")
	cat("\t\t<arrayID>: the batch ID from 1 to ")
        cat("\tOutput:\n")
        cat("\t\t<Out_Prefix>_*.Rdata will be generated.\n")
        q(save="no")
}

gc()

## load required packages
library(gdsfmt)
library(SeqArray)
library(SeqVarTools)
library(STAAR)
library(STAARpipeline)

###########################################################
#           User Input
###########################################################
## aGDS directory
agds_dir <- get(load(paste0(args[1],"/agds_dir.Rdata")))
## Annotation channel
Annotation_name_catalog <- get(load(paste0(args[1],"/Annotation_name_catalog.Rdata")))

## Null model
obj_nullmodel <- genesis2staar_nullmodel(readRDS(args[2]))
#obj_nullmodel <- get(load(args[2]))

## QC_label
QC_label <- "annotation/filter"
## variant_type
variant_type <- "variant"
## geno_missing_imputation
geno_missing_imputation <- "mean"

## Annotation_dir
Annotation_dir <- "annotation/info/FunctionalAnnotation"
## Use_annotation_weights
Use_annotation_weights <- TRUE
## Annotation name
Annotation_name <- c("CADD","LINSIGHT","FATHMM.XF","aPC.EpigeneticActive","aPC.EpigeneticRepressed","aPC.EpigeneticTranscription",
                     "aPC.Conservation","aPC.LocalDiversity","aPC.Mappability","aPC.TF","aPC.Protein")

## output path
output_path <- args[4]

arrayid <- as.numeric(args[3])

###########################################################
#           Main Function 
###########################################################
## gene number in job
gene_num_in_array <- 50

# genes_info is from library(STAARpipeline)
# Format is: CHKB-CPT1B 22 50568869 50582965
# There are 18445 in the table.
group.num.allchr <- ceiling(table(genes_info[,2])/gene_num_in_array)
sum(group.num.allchr) # Total jobs

chr <- which.max(arrayid <= cumsum(group.num.allchr))
group.num <- group.num.allchr[chr]

if (chr == 1){
   groupid <- arrayid
}else{
   groupid <- arrayid - cumsum(group.num.allchr)[chr-1]
}

genes_info_chr <- genes_info[genes_info[,2]==chr,]
sub_seq_num <- dim(genes_info_chr)[1]

if(groupid < group.num)
{ 
	sub_seq_id <- ((groupid - 1)*gene_num_in_array + 1):(groupid*gene_num_in_array)
}else
{
	sub_seq_id <- ((groupid - 1)*gene_num_in_array + 1):sub_seq_num
}	

### exclude large genes
jobid_exclude <- c(21,39,44,45,46,53,55,83,88,103,114,127,135,150,154,155,163,164,166,180,189,195,200,233,280,285,295,313,318,319,324,327,363,44,45,54)
sub_seq_id_exclude <- c(1009,1929,182,214,270,626,741,894,83,51,611,385,771,493,671,702,238,297,388,352,13,303,600,170,554,207,724,755,1048,319,324,44,411,195,236,677)
	
for(i in 1:length(jobid_exclude))
{
	if(arrayid==jobid_exclude[i])
	{
		sub_seq_id <- setdiff(sub_seq_id,sub_seq_id_exclude[i])
	}
}

### gds file
gds.path <- agds_dir[chr]
genofile <- seqOpen(gds.path)

print(gds.path)

genes <- genes_info

results_noncoding <- c()
obj_nullmodel$Sigma_i <- as(obj_nullmodel$Sigma_i, 'dsCMatrix')
for(kk in sub_seq_id)
{
	print(kk)
	gene_name <- genes_info_chr[kk,1]
	print(gene_name)
	results <- Gene_Centric_Noncoding(chr=chr,gene_name=gene_name,genofile=genofile,obj_nullmodel=obj_nullmodel,
	                                  rare_maf_cutoff=0.01,rv_num_cutoff=2,
	                                  QC_label=QC_label,variant_type=variant_type,geno_missing_imputation=geno_missing_imputation,
	                                  Annotation_dir=Annotation_dir,Annotation_name_catalog=Annotation_name_catalog,
	                                  Use_annotation_weights=Use_annotation_weights,Annotation_name=Annotation_name)
	print("Done")
	
	results_noncoding <- append(results_noncoding,results)
}

save(results_noncoding,file=paste0(output_path,"_",arrayid,".Rdata"))

seqClose(genofile)
